[package]
name = "connect4_multiplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-escapes = "0.1.1"
termcolor = "1.2.0"
tokio = { version="1.28.2", features=["full"] }
